sulu_form.only:
    path: /form/only/{key}
    defaults:
        _controller: Sulu\Bundle\FormBundle\Controller\FormWebsiteController::onlyAction

sulu_form.token:
    path: /form/token
    defaults:
        _controller: Sulu\Bundle\FormBundle\Controller\FormWebsiteController::tokenAction
        _requestAnalyzer: false
